name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download release
      run: |
        $url = "https://github.com/sthiriet/star/releases/download/2019.11-rc1/rakudo-star-2019.11-rc1.tar.gz"
        $output = "rakudo-star-2019.11-rc1.tar.gz"
        Invoke-WebRequest -Uri $url -OutFile $output
    - name: set path
      run: |
        echo "##[add-path]${Env:WIX}bin"
        ls -lrt
    - name: Validate prerequisites
      run: |
        $Env:PATH
        perl -v
        gmake -v
        heat -v
        light -v
    - name: configure
      run: |
        perl Configure.pl  --prefix=C:\rakudo --gen-moar
