name: CI

on:
  push:
    branches:
      - master
env:
  releaseName: 2019.11-rc1
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: set path
      run: |
        echo "##[add-path]${Env:WIX}bin"
    - name: Validate prerequisites
      run: |
        $Env:PATH
        perl -v
        gmake -v
        heat -v
        light -v
    - name: Download release
      run: |
        $url = "https://github.com/sthiriet/star/releases/download/${Env:releaseName}/rakudo-star-${Env:releaseName}.tar.gz"
        $output = "rakudo-star-${Env:releaseName}.tar.gz"
        Invoke-WebRequest -Uri $url -OutFile $output
    - name: Extract archive
      run: |
        7z e rakudo-star-${Env:releaseName}.tar.gz -y
        7z x rakudo-star-${Env:releaseName}.tar -y
        ls
    - name: configure
      run: |
        cd rakudo-star-${Env:releaseName}
        perl Configure.pl  --prefix=C:\rakudo --gen-moar
