name: CI

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download release
      uses: fabriciobastian/download-release-asset-action@v1.0.2
      with:
        version: ${{GITHUB_REF}}
        repository: ${{GITHUB_REPOSITORY}}
        file: rakudo-star-${{GITHUB_REF}}.tar.gz
    - name: set path
      run: |
        echo "##[add-path]${Env:WIX}bin"
        ls -lrt
    - name: Validate prerequisites
      run: |
        $Env:PATH
        perl -v
        gmake -v
        heat -v
        light -v
    - name: configure
      run: |
        perl Configure.pl  --prefix=C:\rakudo --gen-moar
