name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download release
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: ${{ env.GITHUB_REPOSITORY }}
        tag: '2019.11-rc1'
        path: downloads
        file: rakudo-star-2019.11-rc1.tar.gz
    - name: set path
      run: |
        echo "##[add-path]${Env:WIX}bin"
        ls -lrt
    - name: Validate prerequisites
      run: |
        $Env:PATH
        perl -v
        gmake -v
        heat -v
        light -v
    - name: configure
      run: |
        perl Configure.pl  --prefix=C:\rakudo --gen-moar
