name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set path
      run: |
        echo "##[add-path]${Env:WIX}bin"
    - name: Validate prerequisites
      run: |
        $Env:PATH
        perl -v
        gmake -v
        heat -v
        light -v
    - name: configure
      run: |
        perl Configure.pl  --prefix=C:\rakudo --gen-moar
