name: CI

on:
  push:
    branches:
      - master
env:
  releaseName: 2019.11-rc1
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up Perl
      run: |
        choco install strawberryperl
        echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
    - name: set path
      run: |
        echo "##[add-path]${Env:WIX}bin"
    - name: Validate prerequisites
      run: |
        $Env:PATH
        perl -v
        gmake -v
        heat -v
        light -v
    - name: Download release
      run: |
        $url = "https://github.com/sthiriet/star/releases/download/${Env:releaseName}/rakudo-star-${Env:releaseName}.tar.gz"
        $output = "rakudo-star-${Env:releaseName}.tar.gz"
        Invoke-WebRequest -Uri $url -OutFile $output
    - name: Extract archive
      run: |
        7z e rakudo-star-${Env:releaseName}.tar.gz -y
        7z x rakudo-star-${Env:releaseName}.tar -y
        ls
    - name: configure
      run: |
        cd rakudo-star-${Env:releaseName}
        perl Configure.pl  --prefix=C:\rakudo --gen-moar
    - name: make install
      run: |
        gmake install
    - name: Build Msi
      run: |
        cd rakudo-star-${Env:releaseName}
        cp c:\strawberry\perl\bin\libgcc_s_sjlj-1.dll c:\rakudo\bin
        cp c:\strawberry\perl\bin\libwinpthread-1.dll c:\rakudo\bin
        cp c:\strawberry\perl\bin\libgcc_s_seh-1.dll c:\rakudo\bin
        gmake msi
        cp rakudo-star*msi rakudo-star-${Env:releaseName}.msi
    - name: release msi
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/sthiriet/star/releases/${Env:releaseName}/assets
        asset_path: rakudo-star-${Env:releaseName}/rakudo-star-${Env:releaseName}.msi
        asset_name: rakudo-star-${Env:releaseName}.msi
        asset_content_type: application/x-msi