name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download release
      run: |
        perl -e 'use File::Fetch; 
        my $ff=File::Fetch->new(uri => "https://github.com/sthiriet/star/releases/download/2019.11-rc1/rakudo-star-2019.11-rc1.tar.gz"); 
        my $file = $ff->fetch() or die $ff->error;'
    - name: set path
      run: |
        echo "##[add-path]${Env:WIX}bin"
        ls -lrt
    - name: Validate prerequisites
      run: |
        $Env:PATH
        perl -v
        gmake -v
        heat -v
        light -v
    - name: configure
      run: |
        perl Configure.pl  --prefix=C:\rakudo --gen-moar
