name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download release
      uses: fabriciobastian/download-release-asset-action@v1.0.2
      with:
        version: 2019.11-rc1
        repository: ${{ env.GITHUB_REPOSITORY }}
        file: rakudo-star-2019.11-rc1.tar.gz
    - name: set path
      run: |
        echo "##[add-path]${Env:WIX}bin"
        ls -lrt
    - name: Validate prerequisites
      run: |
        $Env:PATH
        perl -v
        gmake -v
        heat -v
        light -v
    - name: configure
      run: |
        perl Configure.pl  --prefix=C:\rakudo --gen-moar
