name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Validate prerequisites
      run: |
        perl -v
        gmake -v
        heat -v
        light -v
